01b: lazy
cdkrot/au-java pull request #18
Opened 2018-03-05 12:16 UTC by cdkrot

2018-03-07 07:10 UTC, jzuken requested changes

2018-03-07 07:10 UTC, jzuken commented on term4/01b/src/me/cdkrot/lazy/Lazy.java
> +public interface Lazy<T> {
доки где-то потерялись

2018-03-07 07:10 UTC, jzuken commented
и хорошо бы Travis или что-то подобное настроить, чтобы он делал автоматическую сборку и запуск тестов

2018-06-14 07:41 UTC, jzuken commented
к сожалению, и тут тоже дедлайн пропущен, так что тоже баллы пополам

2018-06-14 07:41 UTC, merged

2018-06-15 17:33 UTC, cdkrot commented
>> к сожалению, и тут тоже дедлайн пропущен, так что тоже баллы пополам

=(

2018-06-15 17:41 UTC, cdkrot commented
И так доделывать весь этот кошмар не хочется